import Head from "next/head";
import { Banner } from "../components/banner";
import { Footer } from "../components/footer";
import { Header } from "../components/header";
import { LargeCard } from "../components/large-card";
import { MediumCard } from "../components/medium-card";
import { SmallCard } from "../components/small-card";

export default function Home({ exploreData, cardData }) {
  return (
    <div className="">
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard key={img} img={img} distance={distance} location={location} />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>
        <LargeCard title="The Greatest Outdoors" description="Wishlist curated by Airbnb" buttonText="Get Inspired" />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then((res) => res.json());
  const cardData = await fetch("https://www.jsonkeeper.com/b/VHHT").then((res) => res.json());
  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
